GET http://localhost:9000/users
Authorization: Bearer 
###

POST http://localhost:9000/users
Content-Type: application/json

{
    "name":"b",
    "email":"b@b.com",
    "password": "b",
    "confPassword": "b"
}
###
POST http://localhost:9000/login
Content-Type: application/json

{
   "email":"b@b.com",
    "password": "b"
}
###
get http://localhost:9000/token
###
DELETE http://localhost:9000/logout
