GET http://localhost:9000/users
###
GET http://localhost:9000/users
Authorization: Bearer 
###
POST http://localhost:9000/users
Content-Type: application/json

{
    "name":"a",
    "email":"a@a.com",
    "password": "a",
    "confPassword": "a"
}
###
POST http://localhost:9000/login
Content-Type: application/json

{
   "email":"a@a.com",
    "password": "a"
}

